apiVersion: v1
kind: ServiceAccount
metadata:
  name: fitbuddy-sa-auth-service
  namespace: production
  annotations:
    azure.workload.identity/client-id: "YOUR-AZURE-MANAGED-IDENTITY-CLIENT-ID"
  labels:
    azure.workload.identity/use: "true"
---
apiVersion: v1
kind: ServiceAccount
metadata:
  name: fitbuddy-sa-chatbot-service
  namespace: production
  annotations:
    azure.workload.identity/client-id: "YOUR-AZURE-MANAGED-IDENTITY-CLIENT-ID"
  labels:
    azure.workload.identity/use: "true"
---
apiVersion: v1
kind: ServiceAccount
metadata:
  name: fitbuddy-sa-diet-service
  namespace: production
  annotations:
    azure.workload.identity/client-id: "YOUR-AZURE-MANAGED-IDENTITY-CLIENT-ID"
  labels:
    azure.workload.identity/use: "true"
---
apiVersion: v1
kind: ServiceAccount
metadata:
  name: fitbuddy-sa-progress-service
  namespace: production
  annotations:
    azure.workload.identity/client-id: "YOUR-AZURE-MANAGED-IDENTITY-CLIENT-ID"
  labels:
    azure.workload.identity/use: "true"
---
apiVersion: v1
kind: ServiceAccount
metadata:
  name: fitbuddy-sa-user-service
  namespace: production
  annotations:
    azure.workload.identity/client-id: "YOUR-AZURE-MANAGED-IDENTITY-CLIENT-ID"
  labels:
    azure.workload.identity/use: "true"
---
apiVersion: v1
kind: ServiceAccount
metadata:
  name: fitbuddy-sa-workout-service
  namespace: production
  annotations:
    azure.workload.identity/client-id: "YOUR-AZURE-MANAGED-IDENTITY-CLIENT-ID"
  labels:
    azure.workload.identity/use: "true"
---
apiVersion: v1
kind: ServiceAccount
metadata:
  name: fitbuddy-sa-yolo-exercise-service
  namespace: production
  annotations:
    azure.workload.identity/client-id: "YOUR-AZURE-MANAGED-IDENTITY-CLIENT-ID"
  labels:
    azure.workload.identity/use: "true"
---
apiVersion: v1
kind: ServiceAccount
metadata:
  name: fitbuddy-sa-frontend
  namespace: production
  annotations:
    azure.workload.identity/client-id: "YOUR-AZURE-MANAGED-IDENTITY-CLIENT-ID"
  labels:
    azure.workload.identity/use: "true"
