apiVersion: v1
kind: ServiceAccount
metadata:
  name: fitbuddy-sa
  namespace: production
  annotations:
    azure.workload.identity/client-id: "YOUR-AZURE-MANAGED-IDENTITY-CLIENT-ID"
  labels:
    azure.workload.identity/use: "true"
