apiVersion: v1
kind: Service
metadata:
  name: fitbuddy-auth-service
  namespace: production
  labels:
    app: fitbuddy-auth-service
spec:
  selector:
    app: fitbuddy-auth-service
  ports:
    - protocol: TCP
      port: 80
      targetPort: 3001
