name: CI - chatbot-service

on:
  push:
    branches:
      - dev
    tags:
      - 'v*'
    paths:
      - 'services/chatbot-service/**'
      - '.github/workflows/ci-chatbot-service.yml'
      - '.github/workflows/ci-template.yml'
  pull_request:
    branches:
      - main
    paths:
      - 'services/chatbot-service/**'
      - '.github/workflows/ci-chatbot-service.yml'
      - '.github/workflows/ci-template.yml'

concurrency:
  group: ${{ github.workflow }}-${{ github.ref }}
  cancel-in-progress: true

jobs:
  call-template:
    uses: ./.github/workflows/ci-template.yml
    with:
      service-name: 'chatbot-service'
      docker-path: 'services/chatbot-service'
      environment: ${{ github.event_name == 'pull_request' && 'pr' || (startsWith(github.ref, 'refs/tags/v') && 'prod' || 'dev') }}
    secrets: inherit
