name: CI - frontend

on:
  push:
    branches:
      - dev
    paths:
      - 'frontend/**'
      - '.github/workflows/ci-frontend.yml'
      - '.github/workflows/ci-template.yml'

permissions:
  contents: write
  pull-requests: write
  security-events: write

concurrency:
  group: ${{ github.workflow }}-${{ github.ref }}
  cancel-in-progress: true

jobs:
  call-template:
    uses: ./.github/workflows/ci-template.yml
    with:
      service-name: 'frontend'
      docker-path: 'frontend'
      environment: 'dev'
    secrets: inherit
