name: CI - user-service

on:
  push:
    branches:
      - dev
    paths:
      - 'services/user-service/**'
      - '.github/workflows/ci-user-service.yml'
      - '.github/workflows/ci-template.yml'
  pull_request:
    branches:
      - main
    paths:
      - 'services/user-service/**'
      - '.github/workflows/ci-user-service.yml'
      - '.github/workflows/ci-template.yml'

concurrency:
  group: ${{ github.workflow }}-${{ github.ref }}
  cancel-in-progress: true

jobs:
  call-template:
    uses: ./.github/workflows/ci-template.yml
    with:
      service-name: 'user-service'
      docker-path: 'services/user-service'
      environment: ${{ github.event_name == 'pull_request' && 'pr' || 'dev' }}
    secrets: inherit
