name: CI - yolo-exercise-service

on:
  push:
    branches:
      - dev
    paths:
      - 'services/yolo-exercise-service/**'
      - '.github/workflows/ci-yolo-exercise-service.yml'
      - '.github/workflows/ci-template.yml'
  pull_request:
    branches:
      - main
    paths:
      - 'services/yolo-exercise-service/**'
      - '.github/workflows/ci-yolo-exercise-service.yml'
      - '.github/workflows/ci-template.yml'

permissions:
  contents: write
  pull-requests: write
  security-events: write

concurrency:
  group: ${{ github.workflow }}-${{ github.ref }}
  cancel-in-progress: true

jobs:
  call-template:
    uses: ./.github/workflows/ci-template.yml
    with:
      service-name: 'yolo-exercise-service'
      docker-path: 'services/yolo-exercise-service'
      environment: ${{ github.event_name == 'pull_request' && 'pr' || 'dev' }}
    secrets: inherit
